### ISSUE TITLE
Add method to get an individual parameter as a number and not a dataframe

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#10]
This might help if someone is planning to actually use this package for something other than data analysis. The current methods all cater to data analysis more by providing a Pandas data frame as the return value. This might be better if someone is using this to update their backend, or require a single parameter only.

To add:
(something along these lines)
Methods that return a single numerical value, and provide a Null value with a warning if that parameter is not measured by the station.

**Comment by corey-new** [comment]
Hello Milind! I'm a university student looking to contribute to open source projects. I believe that I can tackle this issue involving the implementation of individual methods to get individual data.

**Comment by Milind220** [comment]
@corey-new All yours! Don't hesitate to reach out if you need help :)

**Comment by Milind220** [comment]
@corey-new Any updates on this? Thanks!

**Comment by corey-new** [comment]
> 

@Milind220 I've been working on the function implementation. The only issue I'm having is accessing data using the API for the specific AQI, CO, and NO2 statistics

**Comment by Milind220** [comment]
Hi @corey-new , you don't actually need to access the individual parameter data with different API calls. 
The API provides only one endpoint URL to get air quality data for a city, and then returns all the info as JSON. Your method should parse the JSON and return a single parameter.

Also, after some more thought, it's probably best to have just a one method that returns a single parameter based on what the user enters as an argument. 

So if the user enters 'aqi' as an argument, it parses the JSON and returns only the 'aqi'

**Comment by corey-new** [comment]
@Milind220 Oh okay! Thank you for the clarification, I'll keep you updated on my progress

**Comment by corey-new** [comment]
Hey @Milind220, at this point I've figured out the logic and implemented the function into the dev branch code. However, the only problem I'm running into is that I don't know how to run my updated ozone.py file. 
I'm able to run the package, but the program runs the same (none of my changes) from when I first cloned it to my programming environment (Visual Studio Code with Windows PowerShell). 
For example, I'll add ```print("hello")``` to the ```get_city_air()``` method. When I save the file, run the file, 
data = ```get_city_air('example_city')```, and type data...enter, "hello" will not print out to python terminal. So I'm able to run the code and make changes, but when I run it, it's like there were no changes made to the code. Any idea on what I'm doing wrong?

**Comment by Milind220** [comment]
Hi @corey-new ! Yeahh I think I might be familiar with the problem you're facing.  I need a little more information to be sure though haha.

1. How exactly are you trying to run the code? Are you running it with VS code's run button, or directly from the terminal? Are you importing your version of the package and then trying to use it, or directly attempting to run the ozone.py file?

2. Does your development environment have Ozone installed already, using `pip install ozon3`? If it does, then when you import ozone your env is probably importing the pip installed version of Ozone instead of the locally created one that you're making changes on. This would explain why your changes aren't being shown - your code simply won't be run.  Simple fix though: `pip uninstall ozon3` will get rid of the pip installed version.

Also, if you push your code to your forked repo I could take a look and let you know if everything looks alright.

**Comment by corey-new** [comment]
Thank you @Milind220! Problem resolved, I'm able to test the program now. Sorry for the late respnose

**Comment by corey-new** [comment]
Hello @Milind220, I'm still new to git and tried making a pull request to my own repo, the changes aren't specified right. Not sure how to fix this. I don't want to make a pull request to your repo without the clear changes that were made to the code. Is there anything I can do going forward?

**Comment by Milind220** [comment]
@corey-new hey! Could ya explain to me exactly what's wrong? The process for making a PR is explained in the CONTRIBUTING file.
you have to push commits to your own forked repo, then when everything seems to be working, then create a PR to the Dev branch of ozone.

**Comment by corey-new** [comment]
@Milind220 I just made a pull request for this issue. You can probably see the issue I've been having. I followed the CONTRIBUTING file easily, but could not push my code even when I was on origin. So I just added the file to my branch directly from GitHub. The changes I made are lines 208-214 and 312-347. Sorry for making this complicated.

**Comment by Milind220** [comment]
@corey-new Hi I checked out your code both in the pull request and on your forked repository. I've left a review on your PR which you can check out there.

let me reiterate the process of making a PR:

1. fork the main ozone repo from here
2. clone your forked repo to your computer.
3. switch to the dev branch
4. git remote add origin URL_OF_YOUR_FORK
5. make changes, and only commit once everything you add actually works. You must test your code before submitting it for a PR.
6. push your changes to your forked repo with `git push origin dev`
7. check your fork to make sure it's all there
8. create a PR to the main project

if something doesn't work, let me know what exact step in this process is the problem.
