### ISSUE TITLE
Creation of logo for Ozone package 

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#100]
Ozone currently lacks a logo. A logo goes a long way in making the package feel more professional, and makes the README and documentation site look prettier too!

### Guidelines

- The logo should be related to these keywords: ozone, air, clouds, weather, etc

- Should be in .svg format ideally 

- Gotta be cool!

**Comment by kristinamancini** [comment]
Hold my beer, I got this

**Comment by kristinamancini** [comment]
Here is what I came up with:

![Ozone Logo](https://user-images.githubusercontent.com/85172362/161873596-60122fe9-b34b-4ce5-91af-4ff624f34e8c.svg)

Using Figma, I put ozone (three oxygen molecules) and a cloud in front of what is assumed to be the earth or the air, implying ozone depletion.

**Comment by Milind220** [comment]
@kristinamancini Hey! thank you for the effort. I do have some feedback for your proposed logo though:

* The Ozone air quality package doesn't actually have much to do with ozone depletion. 
* Your logo is a little hard to interpret without your explanation alongside. A simpler, more visually appealing logo might be a better idea. Maybe something like just a fancy looking Ozone molecule, or a cool vector image of a cloud. Something that really feels like 'air'

**Comment by kristinamancini** [comment]
Thanks for the feedback! I used your suggestions and I think this type of design fits a bit better, let me know what you think! 

![OzoneLogo](https://user-images.githubusercontent.com/85172362/163073721-c8472145-0aa1-4b1e-955f-c9c90a225ad5.svg)

**Comment by Milind220** [comment]
@kristinamancini Hey! That's definitely better. Could you make it a nice turquoise colour? I think that'd look nice for an air quality package :)
This colour or something similar might be ideal: #4DD8BF

**Comment by kristinamancini** [comment]
Thanks! Here it is with #4DD8BF color:

![Ozone Logo](https://user-images.githubusercontent.com/85172362/163228173-98d7a37b-6fd9-4f81-aff4-5211d6bb672d.svg)

**Comment by Milind220** [comment]
@kristinamancini I really like that actually! Could you share a high resolution version of it so that we can add it in wherever necessary?

**Comment by kristinamancini** [comment]
Sure thing, how is this?

![Ozone Logo](https://user-images.githubusercontent.com/85172362/163585390-dbdf1d44-474d-4d1d-bb7f-31560e2157ca.svg)

**Comment by Milind220** [comment]
@kristinamancini Great, you can make a PR which changes the README to add in the logo below the Ozone title, and remove the cloud emoji next to Ozone.

For example, this mark-down snippet adds the logo in the centre:
```markdown
<div align=center
     
![163585390-dbdf1d44-474d-4d1d-bb7f-31560e2157ca-2](https://user-images.githubusercontent.com/68847270/163665439-860ba833-d231-4ad7-8606-69a9588124c7.svg)
     
</div>
```

This would look like this:

<div align=center
     
![163585390-dbdf1d44-474d-4d1d-bb7f-31560e2157ca-2](https://user-images.githubusercontent.com/68847270/163665439-860ba833-d231-4ad7-8606-69a9588124c7.svg)
     
</div>

**Comment by lahdjirayhan** [comment]
Should this logo be placed in src/media folder too? @Milind220

**Comment by Milind220** [comment]
@lahdjirayhan Actually yeah, that's better for the sake of consistency
