### ISSUE TITLE
Class docstrings required for the Ozone and URLs class

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#11]
Currently the Ozone and URLs class do not have any class docstrings. These should be added to make the purpose and methods of each class clearer to developers who use the package. The URLs class, for example, should state that it cannot/should not be instantiated.

**Comment by iGotAdigBick** [comment]
Can I take care of this? I'm assuming that I just have to describe the classes and their public methods (if any). Do let me know if there's anything else that I can add

**Comment by Milind220** [comment]
@iGotAdigBick All yours! Let me know if you need help :)
