### ISSUE TITLE
When historical data output is saved as CSV file, the dates column is missing entirely, making the data hard to use

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#116]
Here's what the saved file looks like right now:

<img width="582" alt="Screenshot 2022-04-20 at 4 27 21 PM" src="https://user-images.githubusercontent.com/68847270/164185363-2fbee016-bcec-491e-8b9d-0dce1b4dfda0.png">

And the raw CSV file:

<img width="328" alt="Screenshot 2022-04-20 at 4 27 33 PM" src="https://user-images.githubusercontent.com/68847270/164185460-220b7d8f-7d33-48f5-9a27-9a1185ccb447.png">

As you can see, there's no dates column, which would make this data confusing to work with

**Comment by lahdjirayhan** [comment]
We currently store the date information in the DataFrame's index (technically not a column). Maybe we shouldn't? Should we move the date information onto a column instead of the index? @Milind220

This index is also likely the cause of #114.

**Comment by Milind220** [comment]
@lahdjirayhan I took a look at other air quality datasets, and they mostly do store date information in a column. I think it's a nice simple solution to fix this and #114 (if it is in fact the cause for that)

**Comment by Milind220** [comment]
> **NOTE**: Changing the dates information from the index to a column would also be regarded as a breaking change (I think). This is because the methods of querying the data would be different (columns vs index)
