### ISSUE TITLE
Bug: No way to set custom name for file, if saving data as CSV, Excel or JSON file. Also inconsistency in naming.

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#117]
## Current behaviour

All saved files of the same type have the exact same name. This means that if I try to save multiple CSV files, they just overwrite the previous ones. For example:

* CSV files are named 'air_quality.csv'
* Excel files are named  'air_quality_data.csv'
* Excel files are named  'air_quality_data.json'

## Desired behaviour

* Users should have the option to custom name their files should they choose to save their data as a file. 
* If they choose to save their data as a file instead of a dataframe, a warning should tell users that they should give the file a unique name to avoid previous files from being overwritten.

**Comment by ShootGan** [comment]
I can try to work on that. Can you assign me?

**Comment by lahdjirayhan** [comment]
@ShootGan Of course! See [this section on CONTRIBUTING](https://github.com/Milind220/Ozone/blob/main/CONTRIBUTING.md#get-an-issue-assigned-to-you) about how to make an issue get assigned to you automatically!

**Comment by ShootGan** [comment]
Hold my beer, I got this

**Comment by ShootGan** [comment]
On commit i get error `ImportError: cannot import name '_unicodefun' from 'click' (C:\Users\p_nal\.cache\pre-commit\repo99_g8q2e\py_env-python3.8\
lib\site-packages\click\__init__.py)
`

**Comment by Milind220** [comment]
@ShootGan hey! This is an issue with the pre commit hooks (the thing that checks if your commit follows our style guide or not). This is caused by a slightly outdated version of Black, but has been fixed since in the dev branch.

I'm assuming you've already setup your development environment according to the guidelines in the contributing.md file.
To get the latest updates, you need to pull from the upstream dev branch:
`git pull upstream dev:dev`

Then reinstall the pre-commit hooks
`pre-commit install`

It should work fine with this.
