### ISSUE TITLE
Ozone doesn't import, 'ModuleNotFoundError: No module named 'ozone.historical''

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#119]
Here is the complete error message when I try to import Ozone while using it as a user would.

#### Jupyter Notebook

<img width="1112" alt="Screenshot 2022-04-20 at 4 58 17 PM" src="https://user-images.githubusercontent.com/68847270/164191611-fa5df29a-c2cb-4a68-be73-966ed82d8e34.png">

#### Python file

<img width="790" alt="Screenshot 2022-04-20 at 4 58 00 PM" src="https://user-images.githubusercontent.com/68847270/164191692-64feeb5e-c913-4a6e-9ee9-33075e93c04c.png">

It sounds like it has something to do with the relative import.

**Comment by isi1000** [comment]
I'm having this issue, how can I fix it?

**Comment by Milind220** [comment]
@isi1000 Hey! Still trying to figure out what exactly is going wrong with that import, but we'll have it fixed soon!

If you simply want to use the rest of Ozone's features (non historical data features), you can try using Ozone v1.5.5:
1. `pip uninstall ozon3`
2. `pip install ozon3==1.5.5`

**Comment by Milind220** [comment]
@lahdjirayhan I think I've managed to solve this quite simply. The error appeared to be indicating that it couldn't find the module. By adding an __init__.py  in the historical directory, it turns it into a local package, and the error goes away. I'll confirm this with a testPyPI package upload to check if it has actually worked.

**Comment by lahdjirayhan** [comment]
I didn't see that coming.

---

As for giving `__init__.py`, Maybe you're on the right track. The Python module/package distinction confuses me, maybe that's what got me before.

---

The last image you sent indicates that `relevant_funcs.js` (where the relevant part of JS script lives) isn't present in the Ozone installation. My un-educated guess: this JS file is not packaged and/or installed/copied properly when using installation from PyPI (note to self: we develop using local editable mode, so we miss it).

One hackish workaround would be just taking the content of `relevant_funcs.js` into a long string within a Python file, to make sure it is packaged onto PyPI.

The `_JS_FUNCS` variable in `_reverse_engineering.py` is just a long string, after all.

**Comment by isi1000** [comment]
@lahdjirayhan @Milind220 
It is true that all the historical folder doesn't, download when you use pip, but I added it manually and there is another problem with _reverse_engineering.py and relevant_funcs.js.  
![image](https://user-images.githubusercontent.com/79423137/164321056-2f2bc99c-e555-4734-8200-9ee6856b015e.png)

**Comment by Milind220** [comment]
> Please confirm this if you can, while you're at it @Milind220. Maybe it's the problem.

 Yeah I'll check it out too, though that would make sense!

> If it is, one hackish workaround would be just taking the content of `relevant_funcs.js` into a long triple-quoted string within a Python file, to make sure it is packaged onto PyPI.
> 
> The `_JS_FUNCS` variable in `_reverse_engineering.py` is just a long string, after all.

Hahaha this would work, and that's the main thing. We can go with this.

> EDIT: I've tried installing from test-PyPI in a new separate venv. I can replicate your error @Milind220. When I manually copy-pasted a `relevant_funcs.js` file onto the installation folder (`Ozone-test\venv\Lib\site-packages\ozone\historical`), the error goes away. Seems to reinforce my guess earlier about the .js file not bundled/packaged.

Great! I'll take a look now too :)

**Comment by Milind220** [comment]
@isi1000 Great, seems to confirm what @lahdjirayhan was thinking too!

**Comment by Milind220** [comment]
I could either fix this myself 

OR 👀

@isi1000 Would you like to try fixing this and contributing to Ozone? This is a pretty simple little fix by the looks of it. No worries if you don't want to, of course :)

**Comment by lahdjirayhan** [comment]
Awesome, everyone!

---

> Was the init.py needed at all? or was it just the missing .js file that was wreaking havoc?
> Okay, so it's just the relevant_funcs.js file that was required, not the init.py. Awesome!

I really don't know with regards to init. But judging from the initial error you found: `ModuleNotFoundError: No module named 'ozone.historical'`, it's best to include the init file. Just in case. @Milind220

**Comment by Milind220** [comment]
I'd like to get this fixed asap, so someone _hold my beer, I got this_

**Comment by Milind220** [comment]
Hold my beer, I got this

**Comment by Milind220** [comment]
Fixed this with 0e289df

**Comment by lahdjirayhan** [comment]
I can confirm that the new hotfix solves this issue on my machine.

**Comment by Milind220** [comment]
That's great!

You may notice that the commits in the hotfix didn't pass the pre-commit/pre merge lints. The relevant_funcs.py file kept failing flake8 formatting criteria (lines were 'too long'), and black didn't seem to reformat it at all. At that point I just committed with --no-verify to avoid triggering the pre commit hooks.

**Comment by lahdjirayhan** [comment]
I would say it's safe to just add `# flake8: noqa` to the top of the file. Being just a really long string.

**Comment by Milind220** [comment]
Excellent, I'll add that in
