### ISSUE TITLE
[Breaking Change] params argument lets you enter gibberish and still returns data

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#140]
**Describe the bug**
With the params argument, If you enter correct parameters, it returns valid data. However, if you enter gibberish as a parameter, it returns data with an empty column for that 'parameter'. For example:
```python
get_city_air(city='London', params=['sldkfjsfljsfsf'])
```
would return a dataframe with an empty column called 'sldkfjsfljsfsf'.

**To Reproduce**
1. Use any method which allows you to pass in custom params. Eg: get_city_air
2. Enter in a gibberish parameter
3. See error

**Expected behavior**
Ozone should warn the user that the parameter passed in is invalid, but go ahead and fetch all valid parameters.

**Screenshots**
<img width="847" alt="Screenshot 2022-05-03 at 8 07 21 PM" src="https://user-images.githubusercontent.com/68847270/166449908-c950c3bc-4157-4a27-9e29-656b63088629.png">

**Environment**
 - OS: MacOS
 - Python version 3.9.12
 - Ozone Version 1.7.5
 - Execution Environment: Jupyter Notebook

**Comment by lahdjirayhan** [comment]
Note to future readers:

This behavior is documented in tests, for example this one.

https://github.com/Milind220/Ozone/blob/ba281f5381cfa0a0c8750715d2486457111ff665/tests/test_get_city_air.py#L68-L74

If this behavior needs to change, then the corresponding tests need to also be changed accordingly.

**Comment by Milind220** [comment]
> Note to future readers:
>
> This behavior is documented in tests, for example this one.

@lahdjirayhan Ahhh I do remember reading that. Never quite made the connection that it would also mean that random incorrect parameters would still be a part of the response.

Hmm I do think that it's a good idea to warn users about this. I think the most common situation that this would happen in is if the user has a typo in their code (ex 'pm2.6' instead of 'pm2.5'). Might confuse someone.

**Comment by lahdjirayhan** [comment]
@Milind220 Welp I was thinking it was intended so I accommodated it in tests.

I'll work on this issue.

Hold my beer, I got this

**Comment by lahdjirayhan** [comment]
Now that I'm working on it I realized something. WAQI never returns specific subset of parameters; it always returns full set of parameters. On every request, Ozone downloads full set of air quality parameters (that are available at the requested AQI station). So, why bother giving the `params` argument? Why not just return everything to the user and let them subset it themselves?

However, I may be missing a legitimate use case for the `params` argument to exist. Thoughts? @Milind220

**Comment by Milind220** [comment]
@lahdjirayhan Let's get rid of this in time for version 3.0 then :)
