### ISSUE TITLE
Outdated gifs in README need to be replaced

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#147]
The gifs in the README under the 'examples in action' heading need to be replaced by newer ones. 

The first two gifs do not show any output data. They should be replaced by gifs that show the method as well as the output data.

The third gif's output data is a little outdated at this point. The date information is no longer in the index but in a column, and the pm25 column label has been changed to pm2.5. The gif should show the same method, just with the new output.

**Comment by lahdjirayhan** [comment]
Hold my beer, I got this
