### ISSUE TITLE
Sample output screenshot in README needs to be replaced by new image

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#148]
In the README, under the heading 'sample output' there's a screenshot of the output from one of Ozone's methods.

This image was taken before version 2.0.0, and one of the bugs fixed in v2.0.0 still shows in it. The 'pm25' label across Ozone has now been corrected and changed to 'pm2.5'. 

1) Run the following code in a Jupyter Notebook:
```python
o3.get_city_air('London')
```
2) Add the screenshot to the /src/media directory and label it 'sample-output'
3) Replace the line with the current photo with the path to the image in the media folder

**Comment by Miller2014** [comment]
Hold my beer, I got this
