### ISSUE TITLE
Add a method to show the meaning of the Air Quality Data 

### ISSUE THREAD

**Issue by ubongab** [Milind220/Ozone#17]
For example, an aqi of **0 - 50** is  **Good**  and that means that _air _**quality is considered satisfactory, and air pollution poses little or no risk.**_

**Comment by Milind220** [comment]
@ubongab Yes, sounds like a great idea. 

* Can you try to add this as another column in the dataframe that is returned? Like a column which contains the `AQI_meaning` maybe.
*  Also, refer to the table of meanings for the AQI given in this API documentation page: https://aqicn.org/api/ . I think the 'meaning' column is enough, but feel free to add others too.

**Comment by Milind220** [comment]
That's the page for the API that is used under the hood to fetch the data.

**Comment by ubongab** [comment]
Ok, cool. I'll work on this.
One more question.
Would you prefer to see `AQI_meaning` [Good, moderate....] only or would it be better to include  the `health implications` column as well, to make it more readable and understandable for any simple person requesting the data.
OR better still, shall I condense the two information into one column - `AQI_meaning`? That seems like a robust solution, I presume.

**Comment by Milind220** [comment]
I think include both - more information is a good thing here. 
It's probably best to leave the two as separate columns. Utility wise, it might give people more flexibility with what they want to use and what they don't care about.

**Comment by ubongab** [comment]
Alright, that makes sense!

**Comment by ubongab** [comment]
All done now. PR created. 
Could you please check and if there is anything else that needs changing, please let me know. It's been a pleasure working on this.

**Comment by Milind220** [comment]
@ubongab Checked it out and merged it. Looks like just what we needed! Thanks for all the effort, it's much appreciated!
