### ISSUE TITLE
Need to add a list of links of the World Air Quality Index's API website/documentation to the CONTRIBUTING file

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#19]
Ozone uses the WAQI's API under the hood to fetch its data. Therefore, it's important that contributors can easily find all the information they need about the API in order to make good quality contributions. 

Add a section in the CONTRIBUTING.md file with a list of links to any page that has information that might be important for contributors to know. Also in a single short phrase, describe the page that the link leads to (would help people know which one they need). 

Here's a couple of links to get you started:

WAQI website: https://waqi.info
API overview: https://aqicn.org/api/

**Comment by Tomiiwa** [comment]
Hold my beer, I got this
