### ISSUE TITLE
get_multilple_cities_air() method returns an error

### ISSUE THREAD

**Issue by ubongab** [Milind220/Ozone#21]
Error message:

TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid

**Comment by tariksouabny** [comment]
Are you sure? When I run the following code:
```python
import ozone as ooo
o3 = ooo.Ozone("ec564ca6f5e59e4512bb290f7bfa39fd30cd1df7")
data = o3.get_multiple_city_air(["london", "beijing"])
logging.debug(f"First 5 Lines of the data:\n{data.head(5)}")
```
I get a normal Pandas DataFrame. Can you show some of the code that you used?

**Comment by Milind220** [comment]
I also get  a normal pandas dataframe. I checked both the main and dev branches, and they're both working for me. I used the same code that @tariksouabny  used. 

I suspect that you tried to pass the list of cities to the 'df'  argument, perhaps like this:
```python
test = Ozone('0e0fc4695a0a368fc63ae484dcbfb58953a20985')
    data  = test.get_multiple_city_air(df=['london', 'paris', 'new york'])
```

This also returns the same error that you mentioned.

The df argument is supposed to be used to pass in a Pandas dataframe if you already got some data in a previous get data call. That way you may want to concatenate your existing dataframe with the new dataframe.

**Comment by ubongab** [comment]
Here's what I used.
```
oz = Ozone(API)
m = oz.get_multiple_city_air(["london",  "beijing"])
print(m)
```
It may well be my testing environment. I will open another virtual environment and try to run it again. I'm not sure why I'm getting the error.
`TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid`

**Comment by Milind220** [comment]
@ubongab Hmm that's interesting. 

Let me know when you try it on your new environment and if it works. Also you could try the same code, but explicitly pass in the list of cities as keyword argument.

what version of Python are you using?
