### ISSUE TITLE
README.md: Markdown Code Blocks under "Getting Started" heading are labeled as being shell language - They should be labeled as python

### ISSUE THREAD

**Issue by tariksouabny** [Milind220/Ozone#22]
Under the "Getting Started" section of the README.md, there are two code blocks. In the markdown, these code blocks are labelled as being in the Shell language. However, these code blocks are supposed to be Python. Please label them to be Python

**Current State:**
```
```sh

```
```
```sh
```

**Should be:**
```
```python
```
```
```python
```

**Comment by Milind220** [comment]
Uh Oh, I didn't see this issue, and fixed it in a direct commit right before this. 

Thanks for spotting it! Appreciate it :)

**Comment by tariksouabny** [comment]
No problem!
