### ISSUE TITLE
Add a method to get air quality data for a particular longitude and latitude 

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#29]
Currently users can only get AQI data for a city, or many cities. 

I read into this a little, and the WAQI API offers a URL endpoint to get air quality data for a certain latitude and longitude.  It should be fairly simple to use it and create a method to allow users to get data using geographical coordinates.

Also add a method to get air quality data for an entire list of coordinate pairs (similar to the `get_multiple_city_air`, but for coordinate pairs instead of cities.

Here's the API page with the endpoints: https://aqicn.org/json-api/doc/#api-_

**Comment by Milind220** [comment]
Feel free to reach out for more help on how to go about this, or if you don't understand how to get started

**Comment by antocommi** [comment]
Hi, I'd like to implement this feature. This would be my first contribution ever.

**Comment by Milind220** [comment]
@antocommi Hey, that's awesome! Don't hesitate if you need to reach out for help.

Also, if you're not sure about something you can just open the pull request, and I can give you feedback with the code review - so don't worry, and have fun!

**Comment by antocommi** [comment]
I just made the first method. I'll test it and commit on dev asap

**Comment by antocommi** [comment]
I made a commit with another account that was previously logged in my computer. Could you delete the commit please?
