### ISSUE TITLE
Add method to show air quality forecast information. The API actually returns this info, but we currently ignore it.

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#36]
The WAQI API [documentation](https://aqicn.org/json-api/doc/) mentions how the JSON object that is retuned contains 'forecast' data as well. This is basically the 7 day forecast for 4 parameters: pm25, pm10, o3, and uvi.

Create a method that takes in a city and fetches the forecast data for it. Allow users to enter a list of the specific parameters they want, and get all by default. 

You can refer to the `get_city_air` method while making this. The implementation would be quite similar.

**Comment by antocommi** [comment]
I'll try to implement this feature

**Comment by Milind220** [comment]
@antocommi Awesome!

**Comment by antocommi** [comment]
I currently return a dataframe where there is a column for each prediction with the following name "predictedVariable_i" (e.g. pm10_0, pm10_1, etc... ). Each entry contains the related json value given by the API response. 
```
 {
  "avg": 0,
  "day": "2022-03-09",
  "max": 1,
  "min": 0
}  
```

**Comment by Milind220** [comment]
Hey @antocommi , I just tried out your code and it works fine, but thinking about it now - I don't think the output in the format that we planned is very useful for anyone.

I think it might be a better idea to have your method only let users fetch the forecast data for a single parameter at a time. the columns could be the day, max, min, avg. Each row can represent the forecast for a single day.

What do you think about that idea? Would you like to do it?

**Comment by antocommi** [comment]
Maybe we could add a column to specify the type of variable predicted (e.g. "pm10" ) in order to dinamically get multiple type of predicted variables and save some API calls for the same city/location.

We could let to the user the opportunity to choose which variables to store, all by default. 
`ozone.get_city_forecast(["pm10", "pm25"])`

**Comment by Milind220** [comment]
@antocommi Alright that makes sense. Then each row can represent a day, and each cell would contain data in this format ?
` {
  "avg": 0,
  "day": "2022-03-09",
  "max": 1,
  "min": 0
}  `

**Comment by Milind220** [comment]
That's pretty good, we can specify in the documentation that the data is stored as a dictionary/JSON object, and I'm sure the users would be able to understand how to use it

**Comment by Milind220** [comment]
@antocommi right, but then how would we add in more than one data parameter? 

I suppose it's possible and perhaps a good idea to just add more columns for the other parameters that users might want to fetch. So if they just want pm2.5 for example then the columns are:  day_pm2.5, max_pm2.5, min_pm2.5, avg_pm2.5 

but if they want pm2.5 and o3 then another four columns for day_o3, max_ o3, min_ o3, avg_o3  can be added on

Is that what you're thinking?

**Comment by Sam-damn** [comment]
@antocommi  any updates on this?

**Comment by antocommi** [comment]
Hi, I've been busy lately. I didn't work on this issue.

**Comment by Milind220** [comment]
@antocommi No problem - Are you keen to continue working on this? If not then perhaps you can contribute to Ozone on a future issue

**Comment by Milind220** [comment]
@antocommi Though I've unassigned you from this issue, I'd love your contributions on other issues in the future! It was great working with you :)

**Comment by antocommi** [comment]
No problem! I will come back in a couple of weeks 😃

**Comment by lahdjirayhan** [comment]
I will try to implement this.

**Comment by lahdjirayhan** [comment]
I almost forgot to tell Github to hold my beer, I got this :D

**Comment by lahdjirayhan** [comment]
Currently I have this output format. Is this good? Pandas DataFrame, with MultiIndex columns, and Timestamp Index.

![image](https://user-images.githubusercontent.com/52926983/162990956-a8e8853a-da80-479b-bf2a-4e38797c28e6.png)

For more, take a look at my fork on `forecast` branch, I can continue with a PR if it's okay.

@Milind220

**Comment by Milind220** [comment]
@lahdjirayhan Yesss! This is ideal - can't think of a clearer way to display the data. Go ahead with a PR if you feel it's ready!
