### ISSUE TITLE
Addition of FILE_STRUCTURE.md file to give new contributors clarity on layout of files.

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#37]
Explain the basic file structure and layout of the package in the file. 

* Which directory has the main source code? -> src/ozone/
* Which files have the main classes? ozone.py and urls.py
* What does each of the two files contain? Ozone class, and URLs class
* What are the different files to be edited for dependency management? -> setup.py, requirements.txt, and setup.cfg
* What does src/media contain? -> gifs for README code examples

**Comment by tariksouabny** [comment]
I think that I can do this. However, in what directory do you want the FILE_STRUCTURE.md to be placed in?

**Comment by Sam-damn** [comment]
@tariksouabny the file should be placed in the top most directory, so along side README.md and CONTRIBUTING.md files, i will assign you to this issue :) , in the future if there is any issue you want to be assigned to you can just comment on it by saying:

 "Hold my beer, I got this"
