### ISSUE TITLE
We require a proper API documentation website, for the primary docs of Ozone. The README file cannot explain the methods in enough detail.

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#38]
Any suggestions for what site/service to use?

**Comment by manibi** [comment]
Hey @Milind220, 
We are currently developing a project that automatically generates sufficient & extensive API documentation. It is not ready yet to publish, but we can probably help you within the next 1-2 months if you are interested.

**Comment by Milind220** [comment]
@manibi Hey @manibi !

That sounds like a really awesome project!

We'll probably use something ready-to-use to create our documentation for now, but I think trying out new tools and helping out other projects is great, so I'd love to try it out on Ozone when you're done developing it.
 
Lemme know - either by email or just here on Ozone's repo!
