### ISSUE TITLE
Create a method to get air quality data for all stations a pair of latitude-longitude bounds

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#44]
This should allow users to enter in two pairs of lat-long coordinates. The WAQI API has an [endpoint](https://aqicn.org/json-api/doc/#api-Map_Queries) available to get all air quality measuring stations between two pairs of lat-long pairs. This list of stations could be used with the `get_multiple_coordinate_air` method in Ozone, to get the air quality for all of them.

This would be really useful, as users would essentially be able to get data for an entire area of the world, without necessarily knowing the name/location of each station in that area (Ozone would take care of that part).

Ideally create a private method that takes in a two pairs of lat-long coordinates, and returns a list of several lat-long pairs, one for each station in that range.
Then create a separate method that uses `get_multiple_coordinate_air` under the hood and returns the data in the same way all other data methods do.

**Comment by Sam-damn** [comment]
hello @Milind220  can i work on this?

**Comment by Milind220** [comment]
@Sam-damn That'd be awesome! Your contributions have been 🔥 🔥
