### ISSUE TITLE
List of parameters should be added to docstrings of methods, to allow users to understand what options they have to choose from

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#49]
`[ "aqi", "pm25", "pm10", "o3", "co", "no2", "so2", "dew", "h", "p", "t", "w", "wg" ]`

These are all the separate parameters that the API can get. For each data fetching method, in their docstrings, add the above line and indicate that these are the different options that users can choose from.

**Comment by tariksouabny** [comment]
Not a problem 😎.
Is it also necessary to provide explanations for each of the parameters?

**Comment by Milind220** [comment]
@tariksouabny  No, just add the list of parameters as is. The README contains detailed information about the parameters.

**Comment by Milind220** [comment]
Also, remember to assign yourself to this issue using our new GitHub bot!

**Comment by tariksouabny** [comment]
Hold my beer, I got this
