### ISSUE TITLE
Add the units for the retrieved data in the documentation. As of now, no information about the units of the data is provided.

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#5]
The units will have to be looked up in the WAQI API documentation and added from there. Any units that are missing from there could probably be assumed to be standard units for the parameter being measured. They should be put in the README (later we can add it to the official documentation when we make it)

**Comment by Milind220** [comment]
> Note: The WAQI API website doesn't seem to provide any information about the units of data.

This means that the standard unit for each parameter would probably have to be looked up online and used instead.

**Comment by Tomiiwa** [comment]
Hold my beer, I got this
