### ISSUE TITLE
Create a virtual env setup guide for development of Ozone in the CONTRIBUTING file

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#54]
Using this exact environment is not compulsory, but does help to avoid issues with development of the package's features.

1. Instruct contributors to setup a virtual env with either conda environments or python virtual environments
2. As of now, Python 3.9 should be used ideally (it's what I've used for the majority of the package, and python 3.10 is not yet supported by conda environments)
3. the dependencies should be installed from requirements.txt with `pip install -r requirements.txt`

**Comment by lahdjirayhan** [comment]
Hold my beer, I got this


(I'm testing out the github workflows)

**Comment by Milind220** [comment]
Awesome! Works great :)

**Comment by Milind220** [comment]
@lahdjirayhan Thanks for your contributions! This was a particularly important issue for us to fix!

**Comment by lahdjirayhan** [comment]
Thanks for merging my work as well 😃 @Milind220
