### ISSUE TITLE
The mypy linter, black, and flake8 should be added as development dependencies for the package

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#55]
I've noticed that some contributors make commits that churn up mypy linting warnings. These warnings do not prevent execution of the code, but generally point out a flaw in the design of the program, often to do with type inconsistency.

I think as a part of the development environment, contributors should **ideally** have mypy installed. This also ties in with issue #54 , which has to do with the creation of a consistent development environment for Ozone.

**Comment by Sam-damn** [comment]
i will work on this ,  i think it is important that we get this fixed as soon as possible so that all contributors
have a consistent development environment including my self

**Comment by Milind220** [comment]
@Sam-damn Great! thanks :)
