### ISSUE TITLE
Add restriction on reads/min and reads/ second to prevent token being blocked from API

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#6]
The WAQI API allows a certain number of requests every minute and every second. This can be looked up on their API website. If this limit is exceeded then the users API token is blocked.

An intrinsic check should be added to the code to prevent exceeding this limit, perhaps by taking short breaks between successive requests if the limit is about to be exceeded.

**Comment by Sam-damn** [comment]
Hello 😁, I would love to tackle this issue could I be assigned to it ?

**Comment by Milind220** [comment]
@Sam-damn All yours! Have fun working on it :)

Don't hesitate to ask for help if you need it :)
