### ISSUE TITLE
Add link to the Ozone PyPI package in the README

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#62]
We currently do not have a link to the PyPI page for Ozone (on PyPI it's called ozon3). This is generally a good idea for the sake of completeness.

[This](https://pypi.org/project/ozon3/) is the page that should be linked.

Add the link in the section of the README that instructs users on how to download the package using pip.

**Comment by Milind220** [comment]
@AliShahpurwala hey! No worries, lemme know if you need help with the process :)

Feel free to try another issue after this one! There's some interesting but not too difficult issues that we have listed.

**Comment by Sam-damn** [comment]
Good job! @AliShahpurwala
