### ISSUE TITLE
Create a GitHub action to assign issues to contributors if they comment on an issue saying 'I will do this'

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#71]
This would help ensure that issues are quickly assigned to contributors who express an interest in doing them.
Some steps to help you get started if you're not sure how to go about this:

* [article](https://dev.to/github/assigning-new-contributors-to-issues-using-github-actions-1d27) that covers exactly this. Keep in mind that, for this repo, a user should comment 'I will do this' to get the issue assigned to them

**Comment by Milind220** [comment]
Perhaps we could even make this entertaining, and require contributors to say - "Hold my beer, I got this"

**Comment by Sam-damn** [comment]
Sounds like a fun idea I love it😊
