### ISSUE TITLE
When following development environment setup guide in CONTRIBUTING file, pre-commit install doesn't work right away

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#78]
While following the development environment setup guide from the CONTRIBUTING file, the line that instructs us to do :
`pre-commit install` 

doesn't work right away. I had to pip install pre-commit and then re run the `pre-commit install` for it to work.

* I'm using a conda virtual environment with python 3.9
* Using Zsh

Shouldn't the 'pre-commit' package be added to our dev dependencies in order to have it pre installed before this step?

**Comment by Milind220** [comment]
@lahdjirayhan Figured you'd be able to fix this! If you're interested, it's all yours!

**Comment by Sam-damn** [comment]
@Milind220 isn't pre-commit specified in the requirements.txt

**Comment by Milind220** [comment]
@Sam-damn lol I just realised what I did. I tried this from the main branch instead of dev.

**Comment by Milind220** [comment]
This is what I get for trying to write code at 1 am lol. Sorry about that @Sam-damn @lahdjirayhan

**Comment by Sam-damn** [comment]
ohh lol

**Comment by Sam-damn** [comment]
it is alright hahahahah @Milind220
