### ISSUE TITLE
Addition of tests to check build status

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#8]
The package currently has no test coverage at all. There is thus no method of checking build status with CI/CD.
The core functionality at least should have test coverage.

**Comment by Milind220** [comment]
I'll write the tests for the current core functionality.

**Comment by Sam-damn** [comment]
hey @Milind220 can i take this off your plate?
i always wanted to a implement a test suite , also i feel like this will give me the opportunity to learn more about GitHub actions and workflow and CI/CD and hooks and such.

**Comment by Milind220** [comment]
@Sam-damn Hahaha sure

I've been meaning to get to this for quite a while now, but been bogged down with work. Have fun working on it - After it's complete we can open a new issue to connect the tests to a continuous testing workflow so that you can learn that too!

**Comment by Sam-damn** [comment]
Great! very excited for this :)

**Comment by Milind220** [comment]
@Sam-damn 

* Creating a mock API response to feed into Ozone's methods makes sense - The WAQI API is pretty stable and is unlikely to change anyway, so testing our own code is all we need to do. We should generally remain aware of any changes to the WAQI API though - but perhaps that's a separate issue
* Definitely include some simple tests to check if the urls are what they should be - all our functionality is built on this
* We can begin with testing only public methods. If our public methods work then we can be confident that the private methods are functioning fine, and if the public methods fail then we can trace it back to the private methods.
* Can always add private method tests afterwards in a separate PR
*

**Comment by lahdjirayhan** [comment]
Looking forward to your PR @Sam-damn :)

**Comment by Milind220** [comment]
@Sam-damn Hey! Are you still working on the unit tests? We definitely need this asap, so let us know if you're too busy to work on it

**Comment by Milind220** [comment]
@

**Comment by Sam-damn** [comment]
@Milind220 i apologize i got a a little busy with job , i think it would be best if someone else is assigned to this.

**Comment by lahdjirayhan** [comment]
I'll take this and try.

Hold my beer, I got this.

**Comment by Milind220** [comment]
@lahdjirayhan Tried the tests! they work perfectly :) Can you confirm that you also get this output?


![Uploading Screenshot 2022-04-23 at 12.32.47 AM.png…]()

**Comment by lahdjirayhan** [comment]
@Milind220 Yes. This is my output:
```
=========================== short test summary info ===========================
FAILED tests/test_get_city_air.py::test_bad_data_format - AssertionError: ass...
FAILED tests/test_get_city_air.py::test_correct_data_format - AssertionError:...
FAILED tests/test_get_city_forecast.py::test_bad_data_format_input - Assertio...
FAILED tests/test_get_city_forecast.py::test_correct_data_format_input - Asse...
FAILED tests/test_get_coordinate_air.py::test_bad_coordinates - vcr.errors.Ca...
FAILED tests/test_get_coordinate_air.py::test_bad_data_format - AssertionErro...
FAILED tests/test_get_coordinate_air.py::test_output_formats - AssertionError...
FAILED tests/test_get_historical_data.py::test_warnings_on_input_combo - Fail...
FAILED tests/test_get_historical_data.py::test_correct_data_format - Assertio...
FAILED tests/test_get_multiple_city_air.py::test_return_value_and_format - Va...
FAILED tests/test_get_multiple_city_air.py::test_column_expected_contents - V...
FAILED tests/test_get_multiple_city_air.py::test_column_types - ValueError: c...
FAILED tests/test_get_multiple_city_air.py::test_excluded_params - ValueError...
FAILED tests/test_get_multiple_city_air.py::test_bad_city - ValueError: could...
FAILED tests/test_get_multiple_city_air.py::test_bad_data_format - AssertionE...
FAILED tests/test_get_multiple_city_air.py::test_correct_data_format - ValueE...
FAILED tests/test_get_multiple_coordinate_air.py::test_bad_coordinates - Exce...
FAILED tests/test_get_multiple_coordinate_air.py::test_bad_data_format - Asse...
FAILED tests/test_get_multiple_coordinate_air.py::test_output_formats - Asser...
FAILED tests/test_get_range_coordinates_air.py::test_return_value_and_format
FAILED tests/test_get_range_coordinates_air.py::test_column_expected_contents
FAILED tests/test_get_range_coordinates_air.py::test_column_types - Exception...
FAILED tests/test_get_range_coordinates_air.py::test_excluded_params - Except...
FAILED tests/test_get_range_coordinates_air.py::test_nonexistent_requested_params
FAILED tests/test_get_range_coordinates_air.py::test_bad_data_format - Assert...
FAILED tests/test_get_range_coordinates_air.py::test_output_formats - Excepti...
================== 26 failed, 31 passed in 679.10s (0:11:19) ==================
```

We can incrementally work towards making all the tests pass.
