### ISSUE TITLE
Need better checking for the JSON response

### ISSUE THREAD

**Issue by lahdjirayhan** [Milind220/Ozone#80]
## Problem

It is possible to get a response status code 200 (OK), yet a JSON response like this:
```
{"status": "error", "message": 404"} # clearly does not look like an all-is-good response to me
```

That is, when you call `get_city_air("")` (search for city with empty string as its name). Currently, doing this raises a KeyError.

This is what we have now:

https://github.com/Milind220/Ozone/blob/bef2e410315ac67541448f22296be56c56e90e58/src/ozone/ozone.py#L318-L330

Because the response status code is 200, it passes the first `if` check.

---

## Possible solutions

The immediate fix for this one problem is to check for `response['status'] != 'ok'` before trying to access anything else.

**However**

I think we need more useful response checking. I don't think we need to add more checks into `_check_status_code`, because it already does its job and has perfect scope & purpose. We need to improve the check on JSON response.

If there's a documentation of all possible JSON responses by WAQI, it should help us build a better check.

**Comment by Milind220** [comment]
@lahdjirayhan Good catch - it's definitely possible for bad responses to sneak past the initial if statement. A more comprehensive method to check the API response status would be great here. 

The online [documentation](https://aqicn.org/json-api/doc/) for the WAQI API does show the possible error messages that could accompany a status of Error 4xx.

<img width="586" alt="Screenshot 2022-03-23 at 3 04 10 PM" src="https://user-images.githubusercontent.com/68847270/159668238-fad8c0e2-a89d-4975-b49b-aa7326286625.png">

Seems like a good place to start for this method! What do you think?

**Comment by Milind220** [comment]
@lahdjirayhan Absolutely, let's go with that

**Comment by lahdjirayhan** [comment]
Yeah I'll try and see if I can come up with something. Hold my beer, I got this (hopefully)
