### ISSUE TITLE
Contributors section in README to give credit to all the people who's code helps improve Ozone

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#83]
A section in the README, to give attribution to all the contributors that add code to Ozone. 

Here's a guide to doing this, that I found online:

* https://levelup.gitconnected.com/displaying-contributors-image-on-readme-files-with-no-pain-f1cbaca963e8

**Comment by Tomiiwa** [comment]
Hi, I'd like to work on this documentation

**Comment by Sam-damn** [comment]
@Tomiiwa i have assigned you to work on this, have fun and if you have any questions about it don't hesitate to ask here ;)

**Comment by Tomiiwa** [comment]
Alright, thank you

**Comment by Tomiiwa** [comment]
Hi, the repo isn't coming up on contrib rocks

**Comment by Milind220** [comment]
@Tomiiwa try this out instead maybe:

https://dev.to/lacolaco/introducing-contributors-img-keep-contributors-in-readme-md-gci

**Comment by Tomiiwa** [comment]
![Screenshot (311)](https://user-images.githubusercontent.com/61966277/159943091-87aa615c-7938-454b-b416-ccc6c6960ec7.png)

Still the same link

**Comment by Tomiiwa** [comment]
It worked!

**Comment by Sam-damn** [comment]
great!  @Tomiiwa what was the issue at first?

**Comment by Milind220** [comment]
@Tomiiwa Awesome! How'd you do it?

**Comment by Tomiiwa** [comment]
Contrib.rocks could not find the repo. I tried the samples already on the page and edited to fit the Ozone repo

**Comment by Milind220** [comment]
@Tomiiwa will it automatically update when new contributors add their contributions?

**Comment by Tomiiwa** [comment]
it should, it is linked to the contributors on the repo
