### ISSUE TITLE
Broken link in CONTRIBUTING.md 

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#93]
In the `dev` branch CONTRIBUTING file's Table of Contents, the hyperlink for 'The world air quality index's API' doesn't work.

It is supposed to take you down to the section of the file that it's referring to, but fails to do this. This is probably because of the `'` in the phrase - The world air quality index's API

Pretty easy fix, a simple google search should give you the answer.

(Also whoever takes this, please remember to follow the git commit messages style guide from the CONTRIBUTING file when making commits. For this issue, for example,  the commit should have the prefix [docs]

**Comment by kristinamancini** [comment]
Hold my beer, I got this
